### ISSUE TITLE
Chunk generation broken in Windows

### ISSUE THREAD

**Issue by andylizi** [crxjs/chrome-extension-tools#111]
### Google search terms

* rollup windows path
* rollup relative path windows

### Describe the bug

```js
import '../Users/andylizi/js-react-boilerplate/chunks/shared-dc6c5192.js';
//      ^^^^^^^^ what?

console.log('background script');
```

### How do we reproduce?

1. In **Windows**, clone the offical [JavaScript React boilerplate](https://github.com/extend-chrome/js-react-boilerplate).
2. Ensure latest versions of the plugin and rollup: `npm i -D rollup@latest rollup-plugin-chrome-extension@latest`.
3. In `rollup.config.js`, set `chunkFileNames` to `'chunks/[name]-[hash].js'` i.e. forward slash. Because rollup documention [explicitly said](https://rollupjs.org/guide/en/#outputchunkfilenames):
    > Forward slashes / can be used to place files in sub-directories."

    (a different bug will show up if we don't do this - see below)
4. Create a shared module for code spliting to work with, e.g:
    1. create `src/shared.js` with `console.log('shared')`
    2. add `import '../shared.js'` to `{background, content}/index.js`
5. `npm run build`

### Expected behavior

```js
import '../chunks/shared-dc6c5192.js';

console.log('background script');
```
and `chunks/shared-dc6c5192.js` is generated.

### Actual behavior

an "absolute" path is imported (see description above), and the `chunks` folder with its contents are missing entirely.

### Please complete the following information:

- Library Version: 3.6.2
- Operating System: Windows 10
- Browser: Chrome 94
- Node Version: 16.6.2

### Additional context

Now what if we set `chunkFileNames` to `"chunks\\[name]-[hash].js"` i.e. with Windows slash? Now the imports will be generated correctly and everything would be fine... unless we're using manifest V3. With V3, a different problem would happen:
```json
  "web_accessible_resources": [
    {
      "resources": [
        "chunks\\*-*.js",
        "content\\index.js"
      ],
      "matches": [
        "https://*/*",
        "http://*/*"
      ]
    }
  ]
```
And of course chrome wouldn't handle paths like `content\index.js` and the extension will not load.

This problem, unliked the previous one where I still can't find the reason after hours of debugging, can easily be fixed by
```diff
     const resources = [
       `${chunkFileNames
-        .split('/')
+        .split(/[\/\\]+/)
         .join('/')
         .replace('[format]', '*')
         .replace('[name]', '*')
```
in [src/manifest-input/updateManifest.ts](https://github.com/extend-chrome/rollup-plugin-chrome-extension/blob/2a5623a2938254e902a1089f85946cb57ec7fd0b/src/manifest-input/updateManifest.ts#L58-L64), and is therefore a workaround to the original issue.

**Comment by AmySteam** [comment]
@andylizi thanks for this ✋😎. We did some refactoring this week that will take care of this. Hope to release it early next week. Have a great weekend!

**Comment by jacksteamdev** [comment]
@andylizi Thank you so much for all the work you put into debugging this problem! I don't have a Windows computer to test this on, so your contributions are a big help :muscle: :pray: 

I'm in the process of refactoring this project to support usage with Vite. We won't need `web_accessible_resources` anymore, and I'm going to try to use Rollup's [pluginutils normalizePath](https://github.com/rollup/plugins/tree/master/packages/pluginutils#normalizepath) to fix this Windows path problem once and for all.

**Comment by andylizi** [comment]
Sure, thanks for your great work on this plugin!

**Comment by jacksteamdev** [comment]
Related issue: https://github.com/rollup/rollup/issues/3993

Apparently we've run into this before...

**Comment by jacksteamdev** [comment]
@andylizi RPCE v4 is ready for testing, you can check out [this guide to get started with React](https://dev.to/jacksteamdev/create-a-vite-react-chrome-extension-in-90-seconds-27k1-temp-slug-183199?preview=579c50cd581c92738b08a9ae6850d203f3997be016d1c192c91f80c60b881cb9a3fca0a0a947c0a3af4b05f541b06c563d0abcfd146b01403cfce583), but the same thing works for Svelte.

**Comment by lursyy** [comment]
For me, the only offender was a newly added content script in a subfolder.
My quick and dirty fix was to move it to the root of `src/` and set `output.chunkFileNames` to `"[name]-[hash].js"`.
I don't know why all other files (which also live in subfolders) are not causing this to happen.

@jacksteamdev If I understand correctly, this is already addressed RPCE v4?

**Comment by jacksteamdev** [comment]
@lursyy the next release of RPCE v4 delegates most of the path management to vite, so it should work just fine

**Comment by Cobular** [comment]
Bumping this, just ran into the same issue today. Chunks were not being emitted but they were trying to be imported from a path of the format `.<absolute path to root directory>/chunks/<chunk-filename>.js`. 

Adding the following to my rollup.config.js fixed it (as described in the main post), but I'm not sure if this will work on linux now:
```js
export default {
  ...
  output: {
    ...
    chunkFileNames: "chunks\\[name]-[hash].js",
  },
}
```

I'm on version `3.6.9`, happy to provide any other info.

**Comment by jacksteamdev** [comment]
@Cobular IIRC, this is a weird bug in Rollup. A cross-env workaround:

```javascript
export default {
  output: {
    chunkFileNames: path.join('chunks', '[name]-[hash].js')
  }
}
```

Have you considered using the new Vite plugin? It has true HMR and supports static asset imports out of the box. Basically all the goodness of Vite for Chrome Extensions.

[90 Second Getting Started Guide](https://crxjs.dev/vite-plugin)

**Comment by Cobular** [comment]
> @Cobular IIRC, this is a weird bug in Rollup. A cross-env workaround:
> 
> ```javascript
> export default {
>   output: {
>     chunkFileNames: path.join('chunks', '[name]-[hash].js')
>   }
> }
> ```
> 
> Have you considered using the new Vite plugin? It has true HMR and supports static asset imports out of the box. Basically all the goodness of Vite for Chrome Extensions.
> 
> [90 Second Getting Started Guide](https://crxjs.dev/vite-plugin)

Oh ofc just path.join! 🤦‍♀️ 

Thank you! I'll definitely take a look at the vite plugin next, that sounds great!
