### ISSUE TITLE
Error from file writer: Could not load /react-refresh

### ISSUE THREAD

**Issue by keyding** [crxjs/chrome-extension-tools#255]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [X] In the terminal

### Describe the bug

Refer: [Real Vite-React HMR in Chrome Extension Content Scripts](https://dev.to/jacksteamdev/real-vite-react-hmr-in-chrome-extension-content-scripts-40di)

The css file is not applied.

![1](https://user-images.githubusercontent.com/20431351/159214333-76964a73-3c82-4d2c-95c3-44e9982751db.jpg)

![2](https://user-images.githubusercontent.com/20431351/159214585-7aa57aa7-aa3e-4587-bcfb-00c47d1ca7a1.jpg)

Also, if you install the latest version 4.0.1-18, there are errors

![image](https://user-images.githubusercontent.com/20431351/159214955-5f0a379f-da49-401b-9486-ba0da23c6a01.png)

### Reproduction

https://github.com/keyding/vite-crx-vue-test

### System Info

```shell
System:
    OS: macOS 12.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 132.40 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
  Browsers:
    Brave Browser: 99.1.36.112
    Chrome: 99.0.4844.83
  npmPackages:
    rollup-plugin-chrome-extension: 4.0.1-16 => 4.0.1-16
    vite: ^2.8.0 => 2.8.6
```

### Severity

blocking all usage of RPCE

**Comment by jacksteamdev** [comment]
Only `RPCE@>=4.0.1-18` fully supports content scripts in development.

> Unable to load "/@react-refresh" from server

@keyding RPCE auto-detects if the Vite React plugin is installed and applies the React Refresh preamble to content scripts. 

If the plugin isn't in the config, apparently it can't resolve `/@react-refresh`... 😕 I'll find a better way to auto-detect React usage, I want to keep common use cases (like React) out of the config.

#### Workaround

Try one of these two fixes:

```sh
pnpm rm @vitejs/plugin-react
```

or add `options.contentScripts.preambleCode = false`:

```javascript
// vite.config.js
plugins: [vue(), chromeExtension({ contentScripts: { preambleCode: false } )]
```

LMK if this works for you, I really appreciate your feedback! 🙏

**Comment by jacksteamdev** [comment]
> The css file is not applied.

Only `RPCE@>=4.0.1-18` fully supports content scripts in development.

**Comment by mismith** [comment]
Not OP, but I have the same issue using the latest plugin, and neither the `rm` nor the `preambleCode` option fully fixes the issue (though it does get me past the `/@react-refresh` issue):

<img width="498" alt="image" src="https://user-images.githubusercontent.com/638816/159355567-df841fb1-a8e8-4e2e-8a3f-d1abf32e827e.png">

**Comment by keyding** [comment]
> > Unable to load "/@react-refresh" from server
> 
> @keyding RPCE auto-detects if the Vite React plugin is installed and applies the React Refresh preamble to content scripts. If the plugin isn't in the config, apparently it can't resolve `/@react-refresh`... 😕
> 
> I'll find a better way to auto-detect React usage since I want to keep frequent use cases (like React) out of the config.
> 
> #### Workaround
> Try one of these two fixes:
> 
> ```shell
> pnpm rm @vitejs/plugin-react
> ```
> 
> or add `options.contentScripts.preambleCode = false`:
> 
> ```js
> // vite.config.js
> plugins: [vue(), chromeExtension({ contentScripts: { preambleCode: false } )]
> ```
> 
> LMK if this works for you; I appreciate your feedback! 🙏


Thank you for your reply. 

Follow your method to configure, still not working properly in development. 

(After build, it works fine! 👍)

![image](https://user-images.githubusercontent.com/20431351/159448180-2e32b629-6428-42c9-8f96-47a537005fdf.png)

![image](https://user-images.githubusercontent.com/20431351/159448467-29b3ec44-3231-43b5-ae70-578087300ba7.png)

**Comment by mismith** [comment]
@keyding just to be clear, there’s a typo in the screenshot you posted (`contencontentScripts`); is that accidental or could it be why things still aren’t working for you?

**Comment by keyding** [comment]
@mismith @jacksteamdev It's my spelling mistake. It works fine. Very good.

Thank you very much.

**Comment by jacksteamdev** [comment]
> things are working with build because it doesn’t follow the same path as when running dev

True! build and dev are very different. `contentScripts.preambleCode` is used for HMR (which is serve only). 

> you are importing the names variable of `crx`, but I think the latest version renames that?

`crx` is an alias of `chromeExtension`; both work 👍

**Comment by jacksteamdev** [comment]
> neither the `rm` nor the `preambleCode` option fully fixes the issue

@mismith If you're still looking for a fix, could you create an issue? I don't want your use case to get lost in this issue.

**Comment by mismith** [comment]
> > neither the `rm` nor the `preambleCode` option fully fixes the issue
> 
> @mismith If you're still looking for a fix, could you create an issue? 🙏 I don't want your use case to get lost in this issue.

Thanks for following up @jacksteamdev ! I think my issue was a secondary one, likely related to https://github.com/extend-chrome/rollup-plugin-chrome-extension/issues/270

So I'm good insofar as this thread is concerned 👍
