### ISSUE TITLE
Global constant replacement not working in background worker in dev mode

### ISSUE THREAD

**Issue by andrenanninga** [crxjs/chrome-extension-tools#266]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

Using Vite's [`define`](https://vitejs.dev/config/#define) config to replace a constant doesn't work in background service worker when running dev mode.

In the reproduction repo I have the following in my `vite.config.js`:
```
	define: {
		'__HELLO_WORLD__': '"Hello, World!"'
	}
```

I have two scripts, `main.js` and `background.js`. Both these scripts contain `console.log(__HELLO_WORLD__)`. When I'm running dev mode I can see that in the popup this prints `Hello, World!` to the console. However in the service worker I'm getting the following error `Uncaught ReferenceError: __HELLO_WORLD__ is not defined`.

When running `yarn build` the `__HELLO_WORLD__` constant _is_ replaced in the resulting `background.[hash].js` file. And both the popup and background print `Hello, World` properly.

### Reproduction

https://github.com/andrenanninga/rollup-plugin-chrome-extension-define

### System Info

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 1.47 GB / 16.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 99.0.4844.51
    Edge: 99.0.1150.55
    Firefox: 98.0.1
    Safari: 14.1.2
  npmPackages:
    rollup-plugin-chrome-extension: ^4.0.1-18 => 4.0.1-18
    vite: ^2.8.0 => 2.8.6
```

### Severity

annoyance

**Comment by jacksteamdev** [comment]
@andrenanninga This is working in `@crxjs/vite-plugin@1.0.11` :rocket:
