### ISSUE TITLE
fs-extra causing import problem

### ISSUE THREAD

**Issue by Romybron** [crxjs/chrome-extension-tools#398]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

I wanted to move my project from rollup to Vite and initiating a new project with `npm init vite` + `svelte-ts` and running `npm run build` it told me that `fs-extra` is a CommonJS module and cannot continue.

### Reproduction

1. `npm init vite`
2. select `svelte-ts`
3. add `crx({ manifest })` plugin
4. run `npm run build`

### Logs

```shell
$ vite build
failed to load config from C:\Users\[redacted]\Code\Extensions\vite-project\vite.config.ts
error during build:
file:///C:/Users/[redacted]/Code/Extensions/vite-project/node_modules/rollup-plugin-chrome-extension/dist/index.mjs:7
import fsExtra, { readFile, readFileSync } from 'fs-extra';
                  ^^^^^^^^
SyntaxError: Named export 'readFile' not found. The requested module 'fs-extra' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'fs-extra';
const { readFile, readFileSync } = pkg;
```

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 18.01 GB / 31.93 GB
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (102.0.1245.30)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    rollup-plugin-chrome-extension: ^4.0.1-25 => 4.0.1-25
    vite: ^2.9.9 => 2.9.9
```

### Severity

blocking an upgrade

**Comment by jfdelarosa** [comment]
I just had this issue, solved by removing `"type": "module",` from package.json
I do not know if this will cause any problems later tbh

**Comment by Romybron** [comment]
By removing that the entire app does not work anymore

**Comment by Romybron** [comment]
Using `@crxjs/vite-plugin` instead of `rollup-plugin-chrome-extension@beta` made it work

**Comment by MichaelVidStep** [comment]
I'm still getting this error even when I use @crxjs/vite-plugin
