### ISSUE TITLE
Transpile TypeScript files from `web_accessible_ressources`

### ISSUE THREAD

**Issue by Romybron** [crxjs/chrome-extension-tools#409]
### Describe the problem

Current `vite-plugin@1.0.8` does not transpile TypeScript files from `web_accessible_ressources` like it used to in `rollup-plugin-chrome-extension`.  This was especially useful for injecting JavaScript from `content_scripts` for example.

### Describe the proposed solution

Make it so it transpiles TypeScript files also

### Alternatives considered

My work around for now was to create a new `tsconfig.inject.json` file, which only includes these files and outputs them in `public` folder, and create a new npm script `tsc -p ./tsconfig.inject.json && vite` to transpile them before vite and avoiding the `"ENOENT: Could not load manifest  asset "[file].js". Manifest assets must exist in one of these directories ` error.

### Importance

would make my life easier

**Comment by jacksteamdev** [comment]
@Romybron You can use the import query `?script&module` to inject main world scripts.

```typescript
import injectSrc from './inject?script&module'

const scriptEl = new DOMParser().parseFromString(
`<script src=${chrome.runtime.getUrl(injectSrc)} type="module"></script>
).body.firstElementChild

document.body.append(scriptEl)
```

Changes make the script reload automatically. CRXJS handles web-accessible resources for you. [Read more on DEV](https://dev.to/jacksteamdev/advanced-config-for-rpce-3966#main-world-scripts).

**Comment by Romybron** [comment]
Thank you thats so helpful! I am gonna read more of that DEV post.
I did add `declare module '*?script&module';` to my vite-env.d.ts to make the `"Cannot find module..."` error go away

**Comment by geanrt** [comment]
> @Romybron You can use the import query `?script&module` to inject main world scripts.
> 
> ```ts
> import injectSrc from './inject?script&module'
> 
> const scriptEl = new DOMParser().parseFromString(
> `<script src="${chrome.runtime.getUrl(injectSrc)}" type="module"></script>
> ).body.firstElementChild
> 
> document.body.append(scriptEl)
> ```
> 
> Changes make the entire script reload automatically, and CRXJS handles web-accessible resources for you.
> 
> [Read more on DEV](https://dev.to/jacksteamdev/advanced-config-for-rpce-3966#main-world-scripts)

Thank you, I used this to inject a script into the HOST, you don't need to declare these scripts as web accessible, because in BUILD they all already are, so just inject:

```javascript
import acessPath from './acess?script&module'

const file = chrome.runtime.getURL(acessPath);
const containerEl = document.getElementsByTagName("body")[0];
const scriptEl = document.createElement("script");
scriptEl.setAttribute("type", "text/javascript");
scriptEl.setAttribute("src", file);
containerEl.appendChild(scriptEl);
```
