### ISSUE TITLE
Will solidjs be supported in the future?

### ISSUE THREAD

**Issue by PlayGuitar-CoderQ** [crxjs/chrome-extension-tools#448]
### Describe the problem

Will solidjs be supported in the future?

### Describe the proposed solution

Will solidjs be supported in the future?

### Alternatives considered

Will solidjs be supported in the future?

### Importance

nice to have

**Comment by filipw01** [comment]
Solid is supported. Just use vite plugin for solid

**Comment by PlayGuitar-CoderQ** [comment]
> 

But I tried it and it reports an error, can I ask you to check the error for me? Thank you.

**Comment by promethyttrium** [comment]
> > 
> 
> But I tried it and it reports an error, can I ask you to check the error for me? Thank you.

Can you please post what you have so we can help take a look?

**Comment by PlayGuitar-CoderQ** [comment]
Oh! Sorry I think I've solved it.  😊
