### ISSUE TITLE
Main world scripts cannot be found in dev mode, nor build

### ISSUE THREAD

**Issue by NicolasReibnitz** [crxjs/chrome-extension-tools#573]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [X] In the terminal

### Describe the bug

I'm following the guide [here](https://dev.to/jacksteamdev/advanced-config-for-rpce-3966#main-world-scripts) to inject a main-world script. I face errors in both the dev and build modes.
(note: I'm by no means a typescript expert! That might be the cause of the problem. Just saying).

#### Dev mode
The files compile fine, but the main-world script can't be found.

_See error log below._

The file `dist/src/content-script.ts.js` does exist. `dist/src/main-world.ts__scriptId--MW0JO.js` does not. But there is a `dist/src/main-world.ts.js` file instead.

#### Build mode
The compilation fails.

_See error log below._

(note: I shortened the paths using `[...]` myself. That's not the problem. 😄)

### Reproduction

I put a simplified test case on GitHub here: https://github.com/NicolasReibnitz/crxjs-test-case

I hope that's okay. Let me know if you need something else.

But these are the main files, I guess:

**manifest.config.ts:**

```js
import { defineManifest } from '@crxjs/vite-plugin';
import packageJson from './package.json';

const { version } = packageJson;
const [major, minor, patch, label = '0'] = version.replace(/[^\d.-]+/g, '').split(/[.-]/);

export default defineManifest(async env => ({
	manifest_version: 3,
	name: env.mode === 'staging' ? '[INTERNAL] CRXJS Power Tools' : 'CRXJS Power Tools',
	version: `${major}.${minor}.${patch}.${label}`,
	version_name: version,
	content_scripts: [
		{
			js: ['src/content-script.ts'],
			matches: ['*://192.168.10.1/*']
		}
	]
}));
```

**src/content-script.ts:**

```js
import mainWorld from './main-world?script&module';

const appEl = document.createElement('div');
appEl.id = 'app';
document.body.prepend(appEl);

const script = document.createElement('script');
script.src = chrome.runtime.getURL(mainWorld);
script.type = 'module';
document.head.prepend(script);
```

**src/main-world.ts:**

```js
import { createApp } from 'vue';
import App from './App.vue';

createApp(App).mount('#app');
```

### Logs

Errors in the browser:
```shell
GET chrome-extension://ikdaaeabkbecfogingbieipafiaijibh/src/main-world.ts__scriptId--MW0JO.js net::ERR_FILE_NOT_FOUND
```
and
```
TypeError: Failed to fetch dynamically imported module: chrome-extension://ikdaaeabkbecfogingbieipafiaijibh/src/content-script.ts.js
```

Error in terminal:
```
[crx:dynamic-content-scripts-build] Content script refId is undefined: "import.meta.CRX_DYNAMIC_SCRIPT_bb1f701f,t=document.createElement("div");t.id="insta-cheat";document.body.prepend(t);const e=document.createElement("script");e.src=chrome.runtime.getURL(c);e.type="module";document.head.prepend(e);"
error during build:
Error: Content script refId is undefined: "import.meta.CRX_DYNAMIC_SCRIPT_bb1f701f,t=document.createElement("div");t.id="insta-cheat";document.body.prepend(t);const e=document.createElement("script");e.src=chrome.runtime.getURL(c);e.type="module";document.head.prepend(e);"
    at file:///[...]/crxjs-test-case/node_modules/@crxjs/vite-plugin/dist/index.mjs:803:27
    at String.replace (<anonymous>)
    at Object.generateBundle (file:///[...]/crxjs-test-case/node_modules/@crxjs/vite-plugin/dist/index.mjs:798:43)
    at file:///[...]/crxjs-test-case/node_modules/vite/node_modules/rollup/dist/es/shared/rollup.js:22748:40
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

### System Info

```shell
System:
    OS: macOS 11.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 3.71 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 3.2.1 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.9.0 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Brave Browser: 107.1.45.118
    Chrome: 107.0.5304.87
    Chrome Canary: 109.0.5403.0
    Firefox: 105.0.3
    Firefox Developer Edition: 90.0
    Safari: 16.0
  npmPackages:
    @crxjs/vite-plugin: ^2.0.0-beta.4 => 2.0.0-beta.4 
    vite: ^3.2.0 => 3.2.2
```

### Severity

blocking all usage of RPCE

**Comment by marcoreni** [comment]
I had the same issue, it seemed to go away in dev mode by setting `moduleResolution: node16` (this has some side effects, for example you need to add .js extensions to all the files. See more [here](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#esm-nodejs) ).

I'm still unable to run build script, getting the same `Content script refId is undefined: ` error. Investigating further...

**Comment by marcoreni** [comment]
@NicolasReibnitz after further investigation, the build issue is caused by a wrong regexp.

It's not catched by tests because the test configuration is:
```ts
export default defineConfig({
  build: {
    minify: false,
  },
  [...]
});
```
in fact, by adding `minify: false` to your repo the build command worked. 

I think the `serve` and the `build` issues are different. I will try and submit a PR for the `build` issue, while the `serve` is still rather obscure.

**Comment by jacksteamdev** [comment]
@marcoreni Thanks for the assist and the PR!

**Comment by jacksteamdev** [comment]
@NicolasReibnitz Thanks for putting together this superb issue! The minimum reproduction is a big help. 💯 

There's certainly something fishy going on here. It looks like a file isn't being written; in this case it's `/src/main-world.ts__scriptId--MW0JO.js`, which should be something like `export "/src/main-world.ts.js":`.

It seems that _Vue in the main world_ is somehow tripping up the file writer. I refactored your example to use plain TS in the main world and things seem to work as expected.

As a workaround, I suggest decoupling your main world logic from the Vue app. The Vue app can send messages to the main world script using `window.postMessage` or custom DOM events.

**Comment by NicolasReibnitz** [comment]
Ah... the new build isn't on NPM yet, is it?

**Comment by jacksteamdev** [comment]
Sorry about that! I released it to beta earlier today.

**Comment by NicolasReibnitz** [comment]
Okay, build seems to be working now! Thanks @marcoreni and @jacksteamdev.
Dev doesn't. As expected.
But to my TypeScript-newbie eyes the scripts (including the main-world) seem pretty TypeScript-y already. What did you change @jacksteamdev?

**Comment by marcoreni** [comment]
`transformRequest` for my `injected.ts` file hangs because one of the dependencies fail.
In particular, I have a `tippy.js` dep, that tries to be resolved as `/node_modules/.vite/deps/tippy__js.js?v=2953ce2f`. This resolution goes into [here](https://github.com/crxjs/chrome-extension-tools/blob/main/packages/vite-plugin/src/node/plugin-contentScripts_dynamic.ts#L109) and hangs because `scriptId` is handled, but every other scenario is not.

I honestly don't know whether this is correct.

**Comment by marcoreni** [comment]
After A LOT of try and error I think what's happening here is an infinite loop.

Almost everything works by simply commenting [this line](https://github.com/crxjs/chrome-extension-tools/blob/main/packages/vite-plugin/src/node/plugin-contentScripts_dynamic.ts#L117). I don't have an exact reason, but my assumption is that:
- The plugin starts with a script and traverses all of its dependencies, recursively
- Each dependency some how is, at the same time, being processed by vite
- Vite, for each file, is waiting for all the plugins to end before doing "its stuff"
- The plugin, for each file, is waiting for Vite to end "its stuff".

Therefore, both Vite and the plugin are waiting for each other. 

I don't know why the function is there, I don't know what its purpose is or was supposed to be.

By removing it everything works, I only have an exception inside the chrome console regarding websockets, but I think it's a different issue and I'll detail that in a different thread.
