### ISSUE TITLE
Support built scripts when injected via content script

### ISSUE THREAD

**Issue by jackbach** [crxjs/chrome-extension-tools#576]
### Describe the problem

In my content script I want to inject a script in order to gain access to the main window context:

```js
const s = document.createElement('script');
s.src = chrome.runtime.getURL('script.js');
(document.head || document.documentElement).appendChild(s);
```

([src: method 1](https://stackoverflow.com/a/9517879))

In my script I am importing some npm packages:

```js
import { watch } from 'vue';
```

I am adding script to my manifest:

```json
{
  "web_accessible_resources": [
    {
      "resources": ["script.js"],
      "matches": ["<all_urls>"]
    }
  ]
}
```

`script.js` is built (i can see it in `dist/assets/script.[hash].js`) but `chrome.runtime.getURL('script.js')` gives me apath to a copy of the original file (`dist/script.js`).

I would expect to get a path to the built file.

Thanks for the great job! would be amazing if you could look into it, tell me if I can fix this in another way or if you could fix it.

### Describe the proposed solution

I would expect to get a path to the built file when injecting scripts in content script.

### Alternatives considered

I created a script that I run after build to replace the file names, but it's not a good alternative.

### Importance

i cannot use RPCE without it

**Comment by jacksteamdev** [comment]
@jackbach Thanks for reaching out! You're right. Working with scripts in `web_accessible_resources` gets complicated b/c Vite adds a hash to the filename. You can import a main-world script using the technique from this article:

https://dev.to/jacksteamdev/advanced-config-for-rpce-3966#main-world-scripts

Most of the time, CRXJS handles `web_accessible_resources` automatically, so you can remove the entry for `script.js` from `web_accessible_resources`.

**Comment by jackbach** [comment]
Epic! It works! Thanks :)

**Comment by Harukisatoh** [comment]
I tried to use this solution and it worked, but there's still one issue though.

On the main world script I'm trying to import the package `mobx`, but when I run the app I'm getting this error on console.

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/37125288/235726370-32b3d3e1-a041-454c-9209-5e18c96194f6.png">

From what I can tell the package is not getting into the bundle due to some optimization from vite. I tested a little more and it seems that if I use the `mobx` package somewhere on the content script too (which I was not doing it, I was only using the package on the main world script) the package gets to the final bundle, and the setup starts working.

It's not a elegant solution though, since I don't need to use `mobx` anywhere else, does someone knows a better solution for this?

**Comment by Harukisatoh** [comment]
> I tried to use this solution and it worked, but there's still one issue though.
> 
> On the main world script I'm trying to import the package `mobx`, but when I run the app I'm getting this error on console.
> 
> <img alt="image" width="1188" src="https://user-images.githubusercontent.com/37125288/235726370-32b3d3e1-a041-454c-9209-5e18c96194f6.png">
> 
> From what I can tell the package is not getting into the bundle due to some optimization from vite. I tested a little more and it seems that if I use the `mobx` package somewhere on the content script too (which I was not doing it, I was only using the package on the main world script) the package gets to the final bundle, and the setup starts working.
> 
> It's not a elegant solution though, since I don't need to use `mobx` anywhere else, does someone knows a better solution for this?

After a few hours of research I've found a better solution [here](https://vitejs.dev/guide/dep-pre-bundling.html#customizing-the-behavior). So if you have the same problem than me you can just add this config to your vite.config.ts file:

```js
export default defineConfig({
  // ...
  optimizeDeps: {
    include: ['mobx'], // Here goes the name of the dependency you want Vite to include in the final bundle, in my case 'mobx'
  },
  // ...
});
```

**Comment by beautyfree** [comment]
what if i want to add script from another package? (it's my package which incapsulate dependencies and logic)
