### ISSUE TITLE
popup content is replicating on pages

### ISSUE THREAD

**Issue by 404b** [crxjs/chrome-extension-tools#614]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

Popup content is replicating on pages

### Reproduction

As i have this, html/css elements on App.jsx injecting on pages along with popup

```
import "./index.css";
import App from "./App";

const root = document.createElement("div");
root.id = "crx-root";
document.body.append(root);

render(() => <App />, root);

```

### System Info

```shell
windows 10, chromium 108.0.5359.99
```

### Severity

annoyance

**Comment by Toumash** [comment]
Did you try to doing
```
const root = document.querySelector('#crx-root') || document.createElement("div");
```

?

**Comment by rbhalla** [comment]
Are you able to include your manifest file? It'd be useful to understand how you're including this file.

**Comment by Toumash** [comment]
I would close it as stale. No repro given
