### ISSUE TITLE
Extra content scripts

### ISSUE THREAD

**Issue by wolffparkinson** [crxjs/chrome-extension-tools#687]
### Describe the problem

Currently, content scripts are built based on the scripts specified in `manifest.json`, which is great.

However, there are times when an application would want to inject content scripts based on user interaction. (rather than url matching). In such cases, having an option to build content scripts by specifying it as an `input` field in `rollupOptions` would be really helpful.

The idea is similar to [Extra HTML pages](https://crxjs.dev/vite-plugin/concepts/pages#extra-html-pages) from the official docs.

## Current Behaviour
In the current release `2.0.0-beta.15`, specifying a typescript file in `input` field of `rollupOptions` would not properly import the relative imports from that file.
Minimal repro :
- [with relative imports](https://github.com/wolffparkinson/crxjs-content-script) : results in `UNRESOLVED_IMPORT` error
- [without relative imports](https://github.com/wolffparkinson/crxjs-content-script/tree/0c79d0a3d7c87382155c3d1ef041a902828c757f) : works fine

P.S.
I did not put this under bugs as the library specs do not specify content scripts to be under rollupOptions.input

### Describe the proposed solution

```ts
build: {
    rollupOptions: {
      input: {
           script: "src/content/script.ts"
      },
    },
  },
```

and then in a background worker we can do :
```ts
chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {

  // business logic
  chrome.scripting.executeScript({
    files: ['src/content/script.ts-loader.js'],
    target: { tabId },
  });
});
```

### Alternatives considered

Current workaround is to specify a ghost/non-existing url in manifest.json for the content scripts, so that crxjs would compile them.

```ts
content_scripts: [
    { js: ['src/content/script.ts'], matches: ['https://example.org/foo'] },
  ],
```

and then in the background worker, inject the built scripts.

### Importance

would make my life easier

**Comment by cpakken** [comment]
This feature is already implemented a while back.
I've been using
```ts
// import scriptPath from './content-script?script'

//can execute multiple times
import scriptPath from './content-script?script&module'

chrome.action.onClicked.addListener((tab) => {  
  chrome.scripting.executeScript({
    target: { tabId: tab.id },
    files: [scriptPath]
  });
});
```

I had to go digging and found in jack's blog he wrote last year.
https://dev.to/jacksteamdev/advanced-config-for-rpce-3966

This feature is not well documented. Probably should put this tidbit in
https://crxjs.dev/vite-plugin/getting-started/react/add-content-script

Also in [@crxjs/vite-plugin@2.0.0-beta.16](https://github.com/crxjs/chrome-extension-tools/releases/tag/%40crxjs%2Fvite-plugin%402.0.0-beta.16)

#689 was merged to add `export onExecute()` to allow content script to execute multiple times. 
Is this necessary since `import scriptPath from './content-script?script&module' did the job?

**Comment by wolffparkinson** [comment]
Thanks that is exactly what I was looking for.
It would be great if there that blog link is mentioned somewhere in the docs as well.

**Comment by CruelEngine** [comment]
@cpakken currently using beta.15 and i did try using : import scriptPath from './content-script?script&module' but i keep hitting the error: `cannot use import statement outside a module` when content script with import statement is loaded

**Comment by smeijer** [comment]
Same error as @CruelEngine when trying to inject content scripts:

```js
import otherScript from './other-script?script&module';

chrome.scripting.registerContentScripts([{
  id: 'hook',
  matches: ['<all_urls>'],
  js: [otherScript],
  runAt: 'document_start',
  world: chrome.scripting.ExecutionWorld.MAIN,
}]);
```

**Comment by jameschetwood** [comment]
Having the same issue. Should this issue be reopened?

**Comment by rendomnet** [comment]
can this be done by crx? can we mark some inputs to not use code spliting? content scripts do not allow codespliting.
