### ISSUE TITLE
Can't build the extension for production which has both popup pages and tabs page

### ISSUE THREAD

**Issue by DengSihan** [crxjs/chrome-extension-tools#694]
### Build tool

Vite

### Where do you see the problem?

- [x] In the browser
- [X] In the terminal

### Describe the bug

I'm developing a extension which has both popup page and tabs page.

When in develop mode (`yarn dev`), everything works fine.

But when I try to build for production:

1. `yarn build` can't works correctly, only typescript tips were printed on the console
![image](https://user-images.githubusercontent.com/33658414/233946193-10ecf727-1fd9-48b8-8825-463c91f973ae.png)
（At the tail of the messages: `error Command failed with exit code 1.`)
2. I try to build for production without `tsc`: `yarn vite build`
![image](https://user-images.githubusercontent.com/33658414/233948265-33d9dd02-93bf-4ab1-87c5-2705615de34d.png)
the process was done, but the build can't be accessiable
![image](https://user-images.githubusercontent.com/33658414/233948956-f1262590-3b61-41c3-929d-a09b00573fc2.png)

### Reproduction

[miniest reproduction](https://github.com/DengSihan/crxjs-reproduction)

### System Info

```shell
Windows 10 pro

node v16.18.1

yarn v1.22.19
```

### Severity

annoyance

**Comment by jacksteamdev** [comment]
Thanks for including a reproduction! Looking at the `package.json`, the build script is for `vue-tsc` not `vite`, so what you're seeing for `yarn build` is probably expected and not a CRXJS issue.

## HTML Pages in CRXJS

The manifest needs to include a `action` key to include the popup, there's [an example in the Google Developer docs](https://developer.chrome.com/docs/extensions/mv3/getstarted/development-basics/#build). 

If you want to HTML pages that aren't in the manifest, you can follow [these instructions to include them in the build](https://crxjs.dev/vite-plugin/concepts/pages).
