### ISSUE TITLE
New project doesn't work: Module and MIME type error

### ISSUE THREAD

**Issue by faahim** [crxjs/chrome-extension-tools#714]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

Sorry for the vague title. I have no idea what's going on here, but nothing seems to work, so not sure which part I should point to in the title.

When I'm creating a new project based on the doc, I can't get JS files to work. When opening the pop-up page, or the options page, I get the MIME Type error in the console: `Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

Even the content script is not registering as a module. Whenever I try to import a JS function or a CSS file, I'm getting the error:  `Uncaught SyntaxError: Cannot use import statement outside a module`

I've tried this multiple times with multiple templates, i.e. Ract, Vanilla. I've tried with both Vite stable and Beta. The issue seems to persist in every case. Interestingly though, an existing project seems to work fine and doesn't suffer from any of these issues (at least for now).

I've recently come to love CRXJS and was based quite a few projects on this. With this problem though, I'm basically having to halt all work.

I really appreciate all the amazing work being done on this and hope it'll continue to be developed. 

Looking forward to solving this issue together with you all. 🙃 

### Reproduction

Here's a minimal repo to reproduce the issues mention: https://github.com/faahim/crx-module-and-mime-type-issue

Check out the pop-up page to see the MIME Type/React initialization issue and open up [Google](https://www.google.com) to see the content script issue.

### Logs

```shell
N/A
```

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 57.55 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Brave Browser: 113.1.51.114
    Chrome: 113.0.5672.92
    Firefox: 110.0
    Safari: 16.4
  npmPackages:
    @crxjs/vite-plugin: ^1.0.14 => 1.0.14
    vite: ^2.9.15 => 2.9.15
```

### Severity

blocking all usage of RPCE

**Comment by skmail** [comment]
you probably loaded the src to the browser instead of the dist/ folder.

**Comment by faahim** [comment]
Oh my my my my! 😅 
That was definitely it!

I knew I was doing something incredibly stupid! I feel like such a clown now!!!

<img src="https://media.giphy.com/media/VAkJTA16wGopjslhaA/giphy.gif" />

Thanks a ton, @skmail, I really appreciate the help. Will close the issue.

**Comment by rahulbansal16** [comment]
What was the issue though?
I checked your manifest, only import is src/content.js
![image](https://github.com/crxjs/chrome-extension-tools/assets/8466045/550a7a1c-0b55-4bc5-a066-3ae9ebbac954)

**Comment by rahulbansal16** [comment]
@skmail can you elaborate on the solution?

**Comment by skmail** [comment]
When you run npm run dev, a new folder called dist/ is created which contains the processed and ready-to-use version of your extension, so when you select the src/ folder in the browser, you're selecting the raw code that hasn't been transpiled and  not guaranteed to have the correct linking or compatible syntax specially if you are using external packages which is 100% the case.

You can compare this to app deployment, when deploying a static website, you don't deploy the src/ folder. Instead, you deploy the dist/ or build/ folder to get the website up and running. The same principle applies here, you use the processed version for actual usage, not the raw source code.

**Comment by rahulbansal16** [comment]
So I'm trying to access a file called `onboarding.jsx`. 
This file is in the `dist/src/onboarding.jsx` folder. When I run the extension, the console error says that it is returning MIME type, which means it is able to figure out the location but the MIME type is the issue.

My onboarding.
![image](https://github.com/user-attachments/assets/816554c1-8f89-4703-939b-002d816fc2da)

The location of onboarding.jsx
![image](https://github.com/user-attachments/assets/2df60cbf-5c09-49de-a6c2-6f844125ae9f)

So what do you recommend? Do I replace the source src/onboarding.jsx with dist/src/onboarding.jsx?

**Comment by rahulbansal16** [comment]
So, @skmail skmail, I got the issue when I am packaging the code. It's not converting the JSX to JS.
That's why the file is coming as the text type.

Ideally in the final compiled folder it should be jsx only not js.

What I am missing?
