### ISSUE TITLE
how to use side panel

### ISSUE THREAD

**Issue by cwjjjjj** [crxjs/chrome-extension-tools#729]
### Describe the problem

<img width="476" alt="image" src="https://github.com/crxjs/chrome-extension-tools/assets/93369602/09714ecf-8195-4cc8-87df-a86ef3adc78a">
i want to use side panel , but i can't can my side panel html in dist

### Describe the proposed solution

currently support side panel? If so, how do I need to configure it? If not, when can I support it? Thanks to the author

### Alternatives considered

I hope that the dist can contain the html created in my code. Now no matter how many html files I create, there will only be one in the dist. thanks！

### Importance

would make my life easier

**Comment by JoeyDoey** [comment]
Assuming its the same as while using crx (vite plugin)...

Check if you have the following in your manifest

```json
// rest of manifest.json fields
  "side_panel": {
    "default_path": "sidepanel.html"
  },
    "permissions": [
// other permissions
    "sidePanel"
  ],
  ```
  
I think crx should already handle generating the html if its defined in the manifest but if its not, try explicitly defining the pages to output in the `vite.config.ts` `rollupOptions` like so:
  
  ```typescript
  // rest of vite.config
  build: {
      rollupOptions: {
        input: {
          sidepanel: resolve(root, 'sidepanel.html'),
        },
      },
    },
```
Ref: 
- [chrome.sidePanel - API reference](https://developer.chrome.com/docs/extensions/reference/sidePanel/)
- [CRXJS - Extension Pages](https://crxjs.dev/vite-plugin/concepts/pages)

**Comment by cwjjjjj** [comment]
thanks
