### ISSUE TITLE
Svelte & Vite: background service worker

### ISSUE THREAD

**Issue by neckaros** [crxjs/chrome-extension-tools#740]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [X] In the terminal

### Describe the bug

With npm run dev i get an error in chrome extension screen:
![image](https://github.com/crxjs/chrome-extension-tools/assets/7789770/ffff2458-15b9-4525-a4da-64d97c475b54)

And indeed http://localhost:5173/src/background.ts  gives 404
`Service-worker-loader.js generated:`
```
import 'http://localhost:5173/@vite/env';
import 'http://localhost:5173/@crx/client-worker';
import 'http://localhost:5173/src/background.ts';

```

With npm run build:
![image](https://github.com/crxjs/chrome-extension-tools/assets/7789770/b1046b31-c97d-4a03-9a66-08c6ce037be4)

### Reproduction

Add a background service worker to your manifest.json like so:
```
    "background": {
      "service_worker": "src/background.ts",
      "type": "module"
    },
```
and a src/background.ts file with:
`console.log("test")`

### Logs

```shell
Could not resolve entry module "src/background.ts".
error during build:
RollupError: Could not resolve entry module "src/background.ts".
    at error (file:///E:/devs/redseat-browser/node_modules/rollup/dist/es/shared/node-entry.js:2213:30)
    at ModuleLoader.loadEntryModule (file:///E:/devs/redseat-browser/node_modules/rollup/dist/es/shared/node-entry.js:24240:20)
    at async Promise.all (index 0)
```
```


### System Info

```shell
"@crxjs/vite-plugin": "^2.0.0-beta.12",
    "@sveltejs/vite-plugin-svelte": "^2.0.4",
    "typescript": "^5.0.2",
    "vite": "^4.2.2"

Vite Config:
import { crx } from "@crxjs/vite-plugin";
import { defineConfig } from "vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import manifest from "./manifest.json";

export default defineConfig({
  plugins: [svelte(), crx({ manifest })],
  server: {
    port: 5173,
    strictPort: true,
    hmr: {
      port: 5173,
    },
  }
});
```

### Severity

blocking all usage of RPCE

**Comment by neckaros** [comment]
P.S.: #505 seems related but for sveltekit and only during build

**Comment by neckaros** [comment]
It was a filesystem issue

**Comment by d0whc3r** [comment]
And how did you solve it?
