### ISSUE TITLE
content-script onMessage.addListener doesn't work

### ISSUE THREAD

**Issue by qingchoulove** [crxjs/chrome-extension-tools#747]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

// content/index.ts
```ts
chrome.runtime.onMessage.addListener((message) => {
  console.log("message", message);
});
```
// popup/index.ts

```ts
const onClick = () => {
  console.log("click");
  chrome.runtime.sendMessage("hello");
};

<Button onClick={onClick}>notifications</Button>
```
// defineManifest
```ts
    content_scripts: [
    {
      matches: ["http://*/*", "https://*/*"],
      js: ["src/content/index.tsx"],
    },
  ],
```

### Reproduction

Just follow https://crxjs.dev/vite-plugin/concepts/content-scripts and add the message send and listener。

### Logs

```shell
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
```

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 8.21 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.1 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 9.6.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Safari: 16.5
  npmPackages:
    @crxjs/vite-plugin: ^2.0.0-beta.18 => 2.0.0-beta.18
```

### Severity

annoyance

**Comment by gary-lo** [comment]
I get the same error log @qingchoulove what does it actually mean?

**Comment by qingchoulove** [comment]
When sending messages from `background.js` or `action.js` to `content.js`, you should use `chrome.tabs.sendMessage()`.

**Comment by qingchoulove** [comment]
> I get the same error log @qingchoulove what does it actually mean?


When sending messages from `background.js` or `action.js` to `content.js`, you should use `chrome.tabs.sendMessage()`.
