### ISSUE TITLE
React refresh preamble was not loaded. Something is wrong.

### ISSUE THREAD

**Issue by yanglee2421** [crxjs/chrome-extension-tools#769]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

When using @crxjs/vite-plugin@2 and @vitejs/plugin-react-swc@3 at the same time, the following error occurs in the development mode.

Error：React refresh preamble was not loaded. Something is wrong.

But in production mode, the result generated by build seems to be normal.

### Reproduction

https://github.com/yanglee2421/vite-template/tree/main/crx

### Logs

```shell
Error: React refresh preamble was not loaded. Something is wrong.
    at content.tsx.js:3:33
```

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 36.06 GB / 63.63 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.12 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (115.0.1901.203)
    Internet Explorer: 11.0.22621.1
```

### Severity

blocking an upgrade

**Comment by Toumash** [comment]
Out of curiosity: why not `@vitejs/plugin-react`?

Im using 
```json
    "@crxjs/vite-plugin": "^2.0.0-beta.18",
    "vite": "^4.4.6",
    "typescript": "5.1.6",
    "@vitejs/plugin-react": "^4.0.
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
```

**Comment by yanglee2421** [comment]
Yes, I switched to plugin-react and it solved the problem.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Tomasz ***@***.***>
发送时间: 2023年8月20日 19:30
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [crxjs/chrome-extension-tools] React refresh preamble was not loaded. Something is wrong. (Issue #769)


Out of curiosity: why not @vitejs/plugin-react?

Im using

    ***@***.***/vite-plugin": "^2.0.0-beta.18",

    "vite": "^4.4.6",

    "typescript": "5.1.6",

    ***@***.***/plugin-react": "^4.0.

    "react": "^18.2.0",

    "react-dom": "^18.2.0",

**Comment by Toumash** [comment]
Lets close it then

**Comment by sovetski** [comment]
I have the same problem, I am using `"@vitejs/plugin-react-swc": "^3.5.0",` and `"@crxjs/vite-plugin": "^2.0.0-beta.21"`

**Comment by Toumash** [comment]
> I have the same problem, I am using `"@vitejs/plugin-react-swc": "^3.5.0",` and `"@crxjs/vite-plugin": "^2.0.0-beta.21"`

Use `@vitejs/plugin-react then` :P

I was trying to get the warning into the docs https://github.com/crxjs/chrome-extension-tools/pull/770
