### ISSUE TITLE
Manifest `author` Field Wrongly Typed

### ISSUE THREAD

**Issue by Malix-off** [crxjs/chrome-extension-tools#824]
### Build tool

Vite

### Describe the bug

https://github.com/crxjs/chrome-extension-tools/blob/20faa1590032ef90b4588dea06ca7610a4483248/packages/vite-plugin/src/node/manifest.ts#L43 typing doesn't match [its documentation](https://developer.chrome.com/docs/extensions/mv3/manifest/author/)

### Severity

annoyance

**Comment by JoeyDoey** [comment]
Big CRX fan! Came to post the same. Maybe CRX can inherit from `@types/chrome` and union/extend those types to include the Firefox and additional fields? That way types stay up to date/accurate.

### Author field @types/chrome
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chrome/index.d.ts#L7398-L7400

```ts
 author?: {
            email: string;
        } | undefined;
```

### Author field CRX
https://github.com/crxjs/chrome-extension-tools/blob/main/packages/vite-plugin/src/node/manifest.ts#L43

```ts
author?: string | undefined
```

**Comment by hchangjae** [comment]
Any updates yet?

**Comment by Malix-off** [comment]
Well I guess I will file a pull request today then

**Comment by Malix-off** [comment]
Update:
This was valid in Manifest V2: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/author

**Comment by Malix-off** [comment]
> Maybe CRX can inherit from `@types/chrome` and union/extend those types to include the Firefox and additional fields? That way types stay up to date/accurate.

Yes, that would be the best thing to do

## Related

- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chrome/index.d.ts
