### ISSUE TITLE
Use vite 5

### ISSUE THREAD

**Issue by beautyfree** [crxjs/chrome-extension-tools#835]
### Describe the problem

Vite 5 is not used in dependencies

### Describe the proposed solution

Update vite to v5

**Comment by beautyfree** [comment]
This may not make any sense, so this is a question for discussion

**Comment by birkskyum** [comment]
... why would this not make sense?

**Comment by ffaubert** [comment]
bump

**Comment by akash07k** [comment]
bump

**Comment by AmySteam** [comment]
We've merged #841. @crxjs/vite-plugin@2.0.0-beta.23 is Vite 5 compatible now
