### ISSUE TITLE
Сan’t build a project with vite version newer than 5.0.11

### ISSUE THREAD

**Issue by wokalek** [crxjs/chrome-extension-tools#874]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

I'm trying to build [my project](https://github.com/wokalek/tab-volume) on a version newer than `vite@5.0.11`.

The project is not built on vite@5.1.0 (the newest is vite@5.1.4).

The problem is that the files
dist/src/pages/popup.html
dist/src/pages/offscreen.html

We end up with empty import js files, the <script> tags are simply missing. I suspect that the problem is somewhere inside the crxjs plugin.

### Reproduction

You can update version of my extension to vite@5.1.0 (or 5.1.4) and you will see empy little window after build, couse builded .html files doesn't have any imports.

### System Info

```shell
System:
  OS: Windows 11 10.0.22631
  CPU: (16) x64 AMD Ryzen 7 5700X 8-Core Processor
  Memory: 11.46 GB / 31.93 GB
Binaries:
  Node: 20.11.1 - C:\Program Files\nodejs\node.EXE
  npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  pnpm: 8.15.4 - C:\Program Files\nodejs\pnpm.CMD
Browsers:
  Edge: Chromium (122.0.2365.59)
  Internet Explorer: 11.0.22621.1
npmPackages:
  @crxjs/vite-plugin: 1.0.14 => 1.0.14
  vite: 5.0.11 => 5.0.11
```

### Severity

annoyance

**Comment by Toumash** [comment]
Wow vite 5 with the legacy crx?
Try to use the crx @ beta from a month ago

**Comment by wokalek** [comment]
> Wow vite 5 with the legacy crx? Try to use the crx @ beta from a month ago

Where is repo?

**Comment by Toumash** [comment]
@wokalek does it work?

**Comment by remmel** [comment]
I've just tried that morning, and HMR **does not work** in **default_popup** with vite 4 (4.5.3) or with vite 5 (5.0.11 & 5.2.12), error is:
`Uncaught (in promise) SyntaxError: Failed to construct 'WebSocket': The URL 'ws://localhost:undefined/' is invalid.`
Note that for the versions above HMR works in content script  (tried via manifest.json method)
(vanilla js)

**Comment by wokalek** [comment]
> @wokalek does it work?

@Toumash 

I just tried it, and yes, it works. Thanks a lot.

Both prod mode and dev mode are working just fine with the latest versions of all packages.

![image](https://github.com/crxjs/chrome-extension-tools/assets/23037847/0f434c40-a3b6-4332-bb46-5dac0c537fda)

**Comment by Toumash** [comment]
@wokalek perfect 🎉 lets close the issue then

**Comment by HppZ** [comment]
> I've just tried that morning, and HMR **does not work** in **default_popup** with vite 4 (4.5.3) or with vite 5 (5.0.11 & 5.2.12), error is: `Uncaught (in promise) SyntaxError: Failed to construct 'WebSocket': The URL 'ws://localhost:undefined/' is invalid.` Note that for the versions above HMR works in content script (tried via manifest.json method) (vanilla js, crxjs 2 beta)

same here!

**Comment by remmel** [comment]
> > I've just tried that morning, and HMR **does not work** in **default_popup** with vite 4 (4.5.3) or with vite 5 (5.0.11 & 5.2.12), error is: `Uncaught (in promise) SyntaxError: Failed to construct 'WebSocket': The URL 'ws://localhost:undefined/' is invalid.` Note that for the versions above HMR works in content script (tried via manifest.json method) (vanilla js, crxjs 2 beta)
> 
> same here!

Hi @HppZ , i edit my previous comment with the fix, as I was out of topic
