### ISSUE TITLE
[crx:manifest-post] Content script fileName is undefined: "src/content.ts"

### ISSUE THREAD

**Issue by abhigyantrips** [crxjs/chrome-extension-tools#883]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

I'm utilizing CRXJS with Vite and SolidStart. I've described the manifest in the Vite config, and the `background.ts` file is loading normally. The issue is that the `content-script.ts` file is throwing an error on build.

### Reproduction

The code is available at https://github.com/abhigyantrips/tab-closer/tree/feat/solidjs-rewrite. All mentioned files are available in `src/`. The error is faced on cloning the project and running `npm run build` (after `npm install` :P).

### Logs

```shell
⚙  Building your app...
removing F:/tab-closer/.vinxi/build/ssr


📦 Compiling ssr router...
vinxi building router ssr in http mode
vite v5.2.11 building SSR bundle for production...
"mergeRefs" is imported from external module "@solid-primitives/refs" but never used in "node_modules/@kobalte/utils/dist/index.js".
✓ 118 modules transformed.
.vinxi/build/ssr/service-worker-loader.js               0.05 kB
.vinxi/build/ssr/assets/content.ts-loader-iUh_24Np.js   0.34 kB
.vinxi/build/ssr/manifest.json                          0.93 kB
.vinxi/build/ssr/.vite/manifest.json                    2.32 kB
.vinxi/build/ssr/public/assets/icon-on-128.png          5.78 kB
.vinxi/build/ssr/assets/ssr-CxdLN8pU.css               24.82 kB
.vinxi/build/ssr/popup.js                               0.14 kB
.vinxi/build/ssr/assets/popup.tsx-BZSiFoYh.js           0.14 kB
.vinxi/build/ssr/assets/content.ts-BERceQR4.js          0.18 kB
.vinxi/build/ssr/assets/background.ts-B2ktewxN.js       0.32 kB
.vinxi/build/ssr/settings.js                            0.61 kB
.vinxi/build/ssr/assets/settings.tsx-R0cjdkUR.js        0.61 kB
.vinxi/build/ssr/_...404_.js                            1.46 kB
.vinxi/build/ssr/assets/routing-SYe4eumR.js             7.61 kB
.vinxi/build/ssr/ssr.js                                22.18 kB
✓ built in 5.08s
✔ build done                                                                                                   11:12:29 pm


📦 Compiling client router...
vinxi building router client in client mode
vite v5.2.11 building for production...
virtual:#vinxi/handler/client (1:78): "default" is not exported by "src/entry-client.tsx", imported by "virtual:#vinxi/handler/client".
✓ 169 modules transformed.
x Build failed in 3.06s

 ERROR  [crx:manifest-post] Content script fileName is undefined: "src/content.ts"                              11:12:32 pm  

  at /F:/tab-closer/node_modules/@crxjs/vite-plugin/dist/index.mjs:1654:27
  at Array.map (<anonymous>)
  at /F:/tab-closer/node_modules/@crxjs/vite-plugin/dist/index.mjs:1650:24
  at Array.map (<anonymous>)
  at Object.generateBundle (/F:/tab-closer/node_modules/@crxjs/vite-plugin/dist/index.mjs:1647:66)
  at /F:/tab-closer/node_modules/rollup/dist/es/shared/node-entry.js:19778:40
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)



 ERROR  [crx:manifest-post] Content script fileName is undefined: "src/content.ts"
```

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
    Memory: 1.31 GB / 7.79 GB
  Binaries:
    Node: 21.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.5.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @crxjs/vite-plugin: ^2.0.0-beta.23 => 2.0.0-beta.23
```

### Severity

blocking all usage of RPCE

**Comment by Toumash** [comment]
@abhigyantrips the code is unavailable. No way to reproduce it

**Comment by abhigyantrips** [comment]
Thank you for pointing that out, the error was about `src/content.ts` because I'd tried renaming the file to see if that sorted the issue (nope). I apologize for the confusion in the issue, but I can confirm that the `manifest.ts` file listed the correct filepath.

It was three weeks ago, though. I've since then shifted the extension to Plasmo which is well-updated and fulfilling my requirements. I was actually able to publish the dang thing!

(Also I'll close this issue since it's now irrelevant.)

**Comment by cezaraugusto** [comment]
for anyone hitting this on Vite 8: the trigger is the Rolldown switch. the `crx:manifest-post` step asks the bundler for the emitted chunk of each `content_scripts` entry, and Rolldown keys chunks differently than Rollup, so the lookup returns undefined. workarounds that unblocked people I've talked to:

1. pin `vite@^7` (still Rollup-based) until this is resolved
2. update `@crxjs/vite-plugin` to the latest release — Rolldown compatibility has been landing incrementally
3. check that the manifest references the script with a root-relative path (no leading slash) and that the same file isn't also imported with `?script` elsewhere

disclosure: I maintain Extension.js. I wrote up the root cause in more detail, including the above workarounds, here: https://extension.js.org/docs/migrate/crxjs-content-script-filename-undefined

**Comment by Toumash** [comment]
hm could you please provide a repro @cezaraugusto? I'm using vite 8 with crxjs/vite-plugin 2.7.0 and i dont have such error, also e2e tests are green

**Comment by cezaraugusto** [comment]
@Toumash you're right, my mistake. I can't reproduce it on current `@crxjs/vite-plugin@2.7.0` + Vite 8, and Vite 8/Rolldown support was already handled in #1132. keep up the great work!

**Comment by Toumash** [comment]
I'm glad to hear that, thank you for a super fast response.
If possible please update the article also https://extension.js.org/docs/migrate/crxjs-content-script-filename-undefined
I get that it was a good marketing copy for the comparison at that time, but now it is outdated.
