### ISSUE TITLE
Build fails when development environment works.

### ISSUE THREAD

**Issue by rzfzr** [crxjs/chrome-extension-tools#886]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

Maybe related to #860, I have this commonjs module imported in my background script, works fine during dev, fails when built.
![image](https://github.com/crxjs/chrome-extension-tools/assets/13456224/14f83c39-1825-40a8-b1a7-5339dd7dd804)

### Reproduction

Import the toggl-api module.
The project where I'm seeing this is open source: https://github.com/rzfzr/toboard-extension

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz
    Memory: 14.02 GB / 31.71 GB
  Binaries:
    Node: 18.19.1 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (123.0.2420.97)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @crxjs/vite-plugin: ^1.0.14 => 1.0.14
    vite: ^2.9.9 => 2.9.18
```

### Severity

annoyance

**Comment by rzfzr** [comment]
Forgot to mention, before migrating to crxjs, I was using webpack, and that build system gave me a working version on both dev and release when importing the same module.

**Comment by Toumash** [comment]
@rzfzr can i somehow reproduce your issue?
Which commit should i use? 

Did you resolve it?

**Comment by rzfzr** [comment]
Greetings @Toumash,
I still have this as an issue, [I just ran it from this commit to confirm it](https://github.com/rzfzr/toboard-extension/tree/f61049de83d2eaa45396f43550694ea84f49a798), steps to reproduce:
1. Clone it
2. npm i
3. npm run build
4. importing the extension as unpacked will give that error shown in the screenshot.

I am still investigating this, it seems to be something with the bundling step, when analysing the non-minified backgroud.ts, I can see that the 'client' variable is being declared later, it would be nice to import this package as is, I'm trying to define this import as commonjs by using '@rollup/plugin-commonjs' or 'vite-plugin-commonjs', but no luck yet.

Running the dev version will result in no error, where following the import gets the non-bundled/original version of the package.

Thanks

**Comment by Toumash** [comment]
I've tried updating the config to the one i have in my project and the error is different - now it gives me the `process` i not defined.
Not sure if it helps, but you can see the code here: https://github.com/rzfzr/toboard-extension/pull/5
I dont have any experience with the polyfills so i cannot really fix them easily - probably you know the solution as you added the node polyfills package already.
The alternative is to implement your own api client - its not super complex as it uses static api_key.
https://github.com/Toumash/daily-status/blob/master/DailyStatus.Common/Services/TogglReportApi.cs

You could generate a client with swagger codegen - they have a openapi file
https://engineering.toggl.com/docs/openapi
or import it into Postman and generate javascript code from there

**Comment by rzfzr** [comment]
Very nice, thanks a lot!
