### ISSUE TITLE
Notification in background script unable to load image in assets 

### ISSUE THREAD

**Issue by RoboticWater** [crxjs/chrome-extension-tools#891]
### Build tool

Vite

### Where do you see the problem?

- [ ] In the browser
- [X] In the terminal

### Describe the bug

When creating a notification using an imported image asset in a background script, I get the error `Uncaught (in promise) Error: Unable to download all specified images.` I'm using `chrome.runtime.getURL(reactLogo)` to get the asset URL, and if I put that URL in the browser, I'm able to access the image, so I doubt the problem is the asset itself. 

This error _doesn't_ occur when I provide a URL to a non-cors protected image somewhere on the internet, so it seems to just be an issue loading assets from within the app.

### Reproduction

Background script:
```jsx
import reactLogo from "./assets/react.svg";

chrome.notifications.create(`notification-${Date.now()}`, {
  type: "basic",
  iconUrl: chrome.runtime.getURL(reactLogo),
  title: "Popup.js",
  message: "Hello from popup.js!",
});
```

Manifest:
```json
{
  "manifest_version": 3,
  "name": "CRXJS React Vite Example",
  "version": "1.0.0",
  "permissions": ["storage", "notifications", "tabs"],
  "background": {
    "service_worker": "src/background.ts",
    "type": "module"
  },
  "action": { "default_popup": "index.html" }
}
```

### Logs

```shell
Uncaught (in promise) Error: Unable to download all specified images.
    at extensions::notifications:122:7
    at Object.oncomplete (extensions::notifications:95:9)
    at Object.onerror (extensions::imageUtil:124:17)
    at extensions::imageUtil:62:17
```

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (24) x64 12th Gen Intel(R) Core(TM) i9-12900K
    Memory: 11.95 GB / 31.75 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    npm: 10.7.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.1.0 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (124.0.2478.80)
    Internet Explorer: 11.0.22621.3527
```

### Severity

annoyance

**Comment by Toumash** [comment]
Works just fine for .png but does not for .svg. 
Windows 11 Node 20 Chrome 125.
```
    "vite": "^5.2.11",
    "@crxjs/vite-plugin": "^2.0.0-beta.23",
    "@vitejs/plugin-react": "^4.2.1",
```

```ts
import reactLogo from '../../img/logo.png';
chrome.notifications.create(`notification-${Date.now()}`, {
  type: 'basic',
  iconUrl: chrome.runtime.getURL(reactLogo),
  title: 'Popup.js',
  message: 'Hello from popup.js!',
});
```

Works just fine


![image](https://github.com/crxjs/chrome-extension-tools/assets/9840635/35194bac-cb83-4655-998d-0970e3826c88)

But .svg didnt work
```js
import reactLogo from '../../img/logo.svg';
chrome.notifications.create(`notification-${Date.now()}`, {
  type: 'basic',
  iconUrl: reactLogo,
  title: 'Popup.js',
  message: 'Hello from popup.js!',
});
```

**Comment by Toumash** [comment]
Did it work?
Can we close the issue @Rbo'

**Comment by RoboticWater** [comment]
@Toumash yes, that worked, you can close the issue.

**Comment by Toumash** [comment]
@RoboticWater i cannot close it, youre the author ;)

**Comment by RoboticWater** [comment]
Issue resolved, see [this comment](https://github.com/crxjs/chrome-extension-tools/issues/891#issuecomment-2163920205) for the answer.
