### ISSUE TITLE
Dev Mode is not working after Chrome update

### ISSUE THREAD

**Issue by rendomnet** [crxjs/chrome-extension-tools#929]
### Build tool

Vite

### Where do you see the problem?

- [X] In the browser
- [ ] In the terminal

### Describe the bug

Dev mode is not loading Extension after latest Chrome update. Same build is working in Brave browser.

console
VITE v5.4.0  ready in 438 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help

![image](https://github.com/user-attachments/assets/142a2be6-b595-4ba3-bf73-58c865a15a95)

### Reproduction

Build Vue Vite extension and run it in dev mode of Chrome

### System Info

```shell
System:
    OS: macOS 15.0.1
    CPU: (10) arm64 Apple M2 Pro
    Memory: 4.88 GB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.4 - ~/.nvm/versions/node/v18.20.4/bin/node
    npm: 10.7.0 - ~/.nvm/versions/node/v18.20.4/bin/npm
    pnpm: 9.7.0 - ~/.nvm/versions/node/v18.20.4/bin/pnpm
  Browsers:
    Brave Browser: 128.1.69.153
    Chrome: 130.0.6723.59
    Edge: 129.0.2792.89
    Safari: 18.0.1
  npmPackages:
    @crxjs/vite-plugin: 2.0.0-beta.25 => 2.0.0-beta.25
    vite: ^5.4.0 => 5.4.0
```

### Severity

blocking an upgrade

**Comment by leoyli** [comment]
This is likely because of a chromium bug.  Check with your content-loader out put and maybe apply a code mod like:

```bash
# Chromium 130.0.6723.59 introduced a bug of lazy loading from `chrome.runtime.getURL`.
# The browser mistakenly treat the file as an exotic file, thus failed to load the script.
# The solution is using a relative instead of absolute file path to by modifying the output script.
sed -i '' 's|chrome\.runtime\.getURL||g' "$FILE"
```

**Comment by lomby92** [comment]
Same of #927

**Comment by rendomnet** [comment]
> Same of #927

But then why production is working?

**Comment by lomby92** [comment]
> > Same of #927
> 
> But then why production is working?

I think that is due to how HMR works. You can run the app even in development mode:
```shell
npx tsc && npx vite build --mode development
```
And than, refresh the extension locally in the "chrome://extensions" page.

You will need to redo these steps at every change 😢

**Comment by mr-menno** [comment]
Same issue.  HMR worked in chrome v129, and stopped in chrome v130. (It also worked in edge v129, and stops working in dev mode in v130)

**Comment by mr-menno** [comment]
`Refused to load the script 'chrome-extension://7cf24a4b-ac49-4275-9b2d-116a69fce601/vendor/crx-client-preamble.js' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules' http://localhost:* http://127.0.0.1:*". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

`src/portal-actions.js-loader.js:9`

**Comment by mr-menno** [comment]
There seems to be a change of behavior in chrome.

`chrome.runtime.getURL()` used to return `chrome-extension://<extensionid>`

Starting in v130 of chrome it now appears to return a `chrome-extension://<temporary_guid>` which changes on every reload of the extension (i.e. when you go to `chrome://extensions` and reload).

In the following file: https://github.com/crxjs/chrome-extension-tools/blob/main/packages/vite-plugin/src/client/es/hmr-client-worker.ts

replacing:
`https://github.com/crxjs/chrome-extension-tools/blob/main/packages/vite-plugin/src/client/es/hmr-client-worker.ts`
with:
`const ownOrigin = 'chrome-extension://' + chrome.runtime.id;`

I get back to a working state.  (I just made the change in `node_modules/vite-plugin/dist/index.mjs` to test).

**Comment by mr-menno** [comment]
With a bit more digging, it appears that this piece:

```
const ownOrigin = new URL(chrome.runtime.getURL('/')).origin
self.addEventListener('fetch', (fetchEvent) => {
  const url = new URL(fetchEvent.request.url)
  if (url.origin === ownOrigin) {
    fetchEvent.respondWith(sendToServer(url))
  }
})
```

in that file causes the issue.  Seems that `location.origin` through the browser returns the `chrome-extension://<extensionid>` while `chrome.runtime.getURL()` function returns `chrome-extension://<guid>`.  Both are valid files inside of the extension, but the conflict causes a failed in using crxjs

**Comment by leoyli** [comment]
@mr-menno I apply my own code-mod, the issue is the `content-loader` or something similar uses absolute path from `chrome.runtime.getURL` so I just forced the output bundle to use the relative path. 

More to read:


- https://issues.chromium.org/issues/363027634

- https://groups.google.com/a/chromium.org/g/chromium-extensions/c/Nr3QNKFv74c/m/PYLvA7dOAAAJ?pli=1

- https://github.com/samrum/vite-plugin-web-extension/issues/144

**Comment by rendomnet** [comment]
What is the current solution? Is there going to be a hotfix?

**Comment by rendomnet** [comment]
And why New tab page is broken if this issue is Content Script related?

**Comment by artaiel** [comment]
with Chrome v130 update, both development and production builds across the board fail to load now, resulting with:

```content-script-loader.content.js.js:12 Refused to load the script 'xyz' because it violates the following Content Security Policy directive: "script-src 'self' 'wasm-unsafe-eval' 'inline-speculation-rules'. Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.```

**Comment by mr-menno** [comment]
Upgraded to
2.0.0-beta.26
***@***.***/vite-plugin/v/2.0.0-beta.26>
Solves the issue.

**Comment by Pxeba** [comment]
Yes. After updating to the new beta version everything went back to normal. :point_up:
