### ISSUE TITLE
###  ⚠️  No Changeset found

### ISSUE THREAD

**Issue by Flores-21** [crxjs/chrome-extension-tools#933]
###  ⚠️  No Changeset found

Latest commit: 877af853e4d6e38201a58a870505cff719bd8782

Merging this PR will not cause a version bump for any packages. If these changes should not result in a new version, you're good to go. **If these changes should result in a version bump, you need to add a changeset.**

<details><summary>This PR includes no changesets</summary>

  When changesets are added to this PR, you'll see the packages that this PR includes changesets for and the associated semver types

</details>

[Click here to learn what changesets are, and how to add one](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md).

[Click here if you're a maintainer who wants to add a changeset to this PR](https://github.com/crxjs/chrome-extension-tools/new/dependabot/npm_and_yarn/packages/vite-plugin/rollup-2.79.2?filename=.changeset/long-radios-breathe.md&value=---%0A%22%40crxjs%2Fvite-plugin%22%3A%20patch%0A---%0A%0Abuild(deps)%3A%20bump%20rollup%20from%202.78.1%20to%202.79.2%20in%20%2Fpackages%2Fvite-plugin%0A)

_Originally posted by @changeset-bot[bot] in https://github.com/crxjs/chrome-extension-tools/issues/922#issuecomment-2379569663_

**Comment by Flores-21** [comment]
Klk

**Comment by jacksteamdev** [comment]
Please follow the issue template; what you're asking is unclear.
